### ISSUE TITLE
Error: Certificate has expired

### ISSUE THREAD

**Issue by mxnnn** [zigtools/zls-vscode#63]
The extension is failing upon VSC start-up - observed on version 1.1.8.

### Log
```
2023-02-05 02:13:57.261 [error] Activating extension AugusteRame.zls-vscode failed due to an error:
2023-02-05 02:13:57.261 [error] Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:526:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
```

**Comment by SuperAuguste** [comment]
Just realized I only mentioned this in DMs / in the ZLS Discord and not here, but the reason this is happening is because of a certificate expiry at zig.pm. This is out of my control as I do not own domain / server, so we'll just have to wait for it to be resolved by the person who kindly allowed us to use this domain to host our binaries.

To be honest, now that we have a budget of sorts, we can totally just use our fuzzing DigitalOcean space to host our binaries as well and thus not rely on a third party donating us server space. Something for the future perhaps.

**Comment by NullTesla** [comment]
Can't it work without a certificate?

**Comment by SuperAuguste** [comment]
You could bypass unauthorized rejection, but that would defeat the purpose of using a certificate. Not using a certificate at all is an option too, but I don't feel comfortable sending a binary that you should trust without one. I'm busy at the moment so I can't make the switch to our own infrastructure just yet, but this should be resolved within about 24 hours.

**Comment by SuperAuguste** [comment]
Should be resolved!

**Comment by MasterQ32** [comment]
Sorry for that! :bow:
